### ISSUE TITLE
FastChat推理报错

### ISSUE THREAD

**Issue by robin-programmer** [IEIT-Yuan/Yuan-2.0#140]
模型：Yuan2-2B-hf
transformers==4.39.1
torch==2.2.1

错误信息
ERROR | stderr | Exception in thread Thread-3 (generate):
ERROR | stderr | Traceback (most recent call last):
ERROR | stderr |   File "/opt/miniconda3/envs/yuan2/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
ERROR | stderr |     self.run()
ERROR | stderr |   File "/opt/miniconda3/envs/yuan2/lib/python3.10/threading.py", line 953, in run
ERROR | stderr |     self._target(*self._args, **self._kwargs)
ERROR | stderr |   File "/opt/miniconda3/envs/yuan2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR | stderr |     return func(*args, **kwargs)
ERROR | stderr |   File "/opt/miniconda3/envs/yuan2/lib/python3.10/site-packages/transformers/generation/utils.py", line 1411, in generate
ERROR | stderr |     streamer.put(input_ids.cpu())
ERROR | stderr |   File "/opt/miniconda3/envs/yuan2/lib/python3.10/site-packages/transformers/generation/streamers.py", line 89, in put
ERROR | stderr |     value = value[0]
ERROR | stderr | IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01-ieisystem @Huifu1018
