### ISSUE TITLE
推理出现错误No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

### ISSUE THREAD

**Issue by chesp** [IEIT-Yuan/Yuan-2.0#69]
推理是出现下面的错误，请问是什么原因。用nvidia-smi查询CUDA版本： NVIDIA-SMI 535.104.12 ，Driver Version: 535.104.12， CUDA Version: 12.2

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
[2023-12-25 04:45:14,778] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
File "/workspace/yuan_2.0/code/tools/run_text_generation_server.py", line 64, in
initialize_megatron(extra_args_provider=add_text_generate_args,
File "/workspace/yuan_2.0/code/megatron/initialize.py", line 37, in initialize_megatron
assert torch.cuda.is_available(), 'Megatron requires CUDA.'
AssertionError: Megatron requires CUDA.

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01-ieisystem

**Comment by zhaoxudong01** [comment]
torch.cuda.is_available() 报错，说明torch找不到gpu设备，需要确认启动容器是否用--gpus all的参数。
不知道在最开始创建容器的时候，执行 torch.cuda.is_available() 的结果是否为True，
- 如果是True的话，说明后续的操作破坏了容器环境；
- 如果是False，说明在创建容器的时候就没有正确的检测到设备，或者虚拟机创建容器环境本身存在不兼容的问题。

**Comment by Shawn-IEITSystems** [comment]
@chesp 请问问题是否已解决？
